#!/bin/bash

serve -s frontend -l 3000 >> /log/webLog 2>&1 &

celery -A backend.celery worker --loglevel=info >> /log/celeryLog 2>&1 &

redis-server >> /log/redisLog &

gunicorn -b "0.0.0.0:5000" "backend:app" --workers 9 2>&1 | tee -a /log/serverLog &

wait