#!/bin/bash

#webgui
serve -s frontend -l 3000 >> /log/webLog 2>&1 &

#long-term backend
celery -A backend.celery worker --loglevel=info >> /log/celeryLog 2>&1 &

#long-term backend 2
redis-server >> /log/redisLog &

#backend
gunicorn -b "0.0.0.0:5000" "backend:app" --workers 1 --worker-class eventlet 2>&1 | tee -a /log/serverLog &

wait