# Use the official Python image as a base
FROM python:3.11-slim

# Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire application code
COPY . /app/

# Use CMD for logging
VOLUME [ "/app/output/" ]
CMD ["celery", "-A", "backend.celery", "worker", "--loglevel=info", "-E"]
